---
- name: Start systemd service - systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: started
    enabled: yes
  become: true

- name: Install packages
  community.general.pacman:
    name:
      - reflector
      - pacman-contrib
      - xdg-desktop-portal
      - xdg-user-dirs
    state: present
  become: true

- name: Start systemd service - paccache.timer
  ansible.builtin.systemd:
    name: paccache.timer
    state: started
    enabled: yes
  become: true

- name: Start systemd service - xdg-user-dirs-update.service
  ansible.builtin.systemd:
    name: xdg-user-dirs-update.service
    state: started
    enabled: yes
    scope: user

- name: Update reflector configuration file
  ansible.builtin.template:
    src: reflector.conf.j2
    dest: /etc/xdg/reflector/reflector.conf
    backup: no
    owner: root
    group: root
    mode: 0644
  become: true

- name: Update mirrorlist
  ansible.builtin.template:
    src: mirrorlist
    dest: /etc/pacman.d/mirrorlist
    backup: no
    owner: root
    group: root
    mode: 0644
  become: true

- name: Update pacman.conf
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    backup: no
    owner: root
    group: root
    mode: 0644
  become: true

- name: Import primary key
  become: true
  command: pacman-key --recv-key 3056513887B78AEB  --keyserver keyserver.ubuntu.com
  changed_when: false

- name: Sign primary key
  become: true
  command: pacman-key --lsign-key 3056513887B78AEB
  changed_when: false

- name: Install keyring and mirrorlist
  become: true
  command: pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm
  changed_when: false

- name: Check pacman.conf contents
  command: cat /etc/pacman.conf
  register: pacman_conf_output
  changed_when: false

- name: Add repository to pacman.conf
  become: true
  lineinfile:
    path: /etc/pacman.conf
    line: |
      [chaotic-aur]
      Include = /etc/pacman.d/chaotic-mirrorlist
    insertafter: EOF
  when: "'[chaotic-aur]' not in pacman_conf_output.stdout"
  changed_when: false
  failed_when: false

- name: Start systemd service - systemd-boot-update.service
  ansible.builtin.systemd:
    name: systemd-boot-update.service
    state: started
    enabled: yes
  become: true

- name: Upgrade system
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  become: true

- name: Install yay
  become: true
  community.general.pacman:
    name: yay
    state: present
