---
- name: Main play
  hosts: all
  roles:
    - { role: host_info }
    - { role: swap }
    - { role: basics }
    - { role: base-packages }
    - { role: audio }
    - { role: display_server }
    - { role: nvidia }
    #- { role: 04_desktop }
    #- { role: 05_packages }
    #- { role: 06_microcode, when: install_microcode }
    #- { role: 07_users }
    #- { role: 08_bluetooth, when: enable_bluetooth }
