---
- name: Main play
  hosts: all
  connection: local
  vars_files:
    - default.config.yml
    - config.yml
  tasks:
    - import_tasks: tasks/update.yml
    - import_tasks: tasks/host-info.yml
    - import_tasks: tasks/base-packages.yml
