---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml
    - config.yml

  tasks:
    - import_tasks: tasks/update.yml
    - import_tasks: tasks/base-packages.yml
    - import_tasks: tasks/swap.yml
    - import_tasks: tasks/chaotic-aur.yml
    - import_tasks: tasks/xorg.yml
    - import_tasks: tasks/nvidiagpu.yml
