---
- name: Main play
  hosts: all
  connection: local
  vars_files:
    - default.config.yml
    - config.yml
  tasks:
    - import_tasks: tasks/update.yml
    - import_tasks: tasks/host-info.yml
    - import_tasks: tasks/microcode.yml
    - import_tasks: tasks/base-packages.yml
    - import_tasks: tasks/chaotic-aur.yml
    - import_tasks: tasks/audio.yml
    - import_tasks: tasks/xorg.yml
    - import_tasks: tasks/nvidia.yml
    - import_tasks: tasks/bluetooth.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/desktop.yml
    - import_tasks: tasks/dev-packages.yml
    - import_tasks: tasks/other-packages.yml
    - import_tasks: tasks/sddm.yml
    - import_tasks: tasks/sddm-theme.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/zsh-catppuccin.yml
    - import_tasks: tasks/genssh.yml
    - import_tasks: tasks/dotfiles.yml
