---
- name: Install base packages
  become: true
  community.general.pacman:
    name:
      - base
      - base-devel
      - linux
      - linux-firmware
      - sudo
      - dhcpcd
      - networkmanager
      - openssh
      - nano
      - man-db
      - man-pages
      - wget
      - reflector
      - unzip
      - eza
      - bat
      - dosfstools
      - ntfs-3g
      - fd
      - ffmpeg
      - fzf
      - stow
      - micro
      - pass
      - fastfetch
      - btop
      - geary
      - cpupower
      - turbostat
      - acpi
      - bc
      - p7zip
      - xclip

    state: present
  changed_when: false

- name: Enable NetworkManager
  become: true
  service:
    name: NetworkManager
    enabled: true
  changed_when: false

- name: Enable reflector
  become: true
  service:
    name: reflector
    enabled: true
  changed_when: false
