---
- name: Install Bluetooth stack
  become: true
  pacman:
    name:
      - bluez
      - bluez-utils
      - bluez-plugins
      - pipewire-pulse
    state: present

- name: Enable bluetooth
  become: true
  service:
    name: bluetooth
    enabled: true
  changed_when: false
