---
- name: Install programs from pacman for desktop.
  become: true
  pacman:
    name:
      - nautilus
      - qt5-wayland
      - qt6-wayland
      - slurp
      - swaybg
      - swayimg
      - swaylock
      - wayland
      - wayland-protocols
      - wl-clipboard
      - wtype
      - hyprland
      - hyprpaper
      - hyprpicker
      - waybar
      - waybar-hyprland
      - xdg-desktop-portal-hyprland
      - lxappearance
      - polkit-gnome

- name: Install Hyprland
  shell: paru -S --noconfirm --needed hyprland-git hyprpaper-git hyprpicker-git waybar-hyprland-git
  tags:
    - install
    - desktop

- name: Install AwesomeWM
  become: true
  pacman:
    name:
      - awesome
      - xorg-xinit
      - xorg-server
      - xwallpaper
      - xclip
  tags:
    - install
    - desktop
