---
- name: Install programs from pacman for desktop.
  become: true
  pacman:
    name:
      - nautilus
      - qt5-wayland
      - qt6-wayland
      - slurp
      - swaybg
      - swayimg
      - swaylock
      - swaync
      - wayland
      - wayland-protocols
      - wl-clipboard
      - wtype
      - hyprland
      - hyprpaper
      - hyprlock
      - hyprpicker
      - libnotify
      - waybar
      - xdg-desktop-portal-hyprland
      - lxappearance
      - polkit-gnome
      - layer-shell-qt5
      - qt6-svg
      - qt6-virtualkeyboard
      - qt6-multimedia-ffmpeg
      - wofi
      - pavucontrol

- name: Install programs from yay for desktop
  become: true
  kewlfft.aur.aur:
    name:
      - hyprshot
    use: yay
    state: present
  changed_when: false
