---
# Desktop environment - Wayland desktop components  
- name: Install Wayland desktop components
  become: true
  community.general.pacman:
    name:
      # Desktop components
      - libnotify
      - polkit-gnome
      # File manager
      - nautilus
      # Theming
      - lxappearance
      - gtk4
      - libadwaita
      # Qt support
      - qt6-svg
      - qt6-virtualkeyboard  
      - qt6-multimedia-ffmpeg
    state: present
  changed_when: false

- name: Install AUR desktop packages
  become: true
  kewlfft.aur.aur:
    name:
      - bibata-cursor-theme-bin
    use: yay
    state: present
  changed_when: false