---
- name: Clone dotfiles repo
  git:
    repo: "https://github.com/dzannotti/dotfiles"
    dest: "{{ ansible_env.HOME }}/dotfiles"
    version: master
    update: true

- name: Ensure correct ownership of dotfiles directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/dotfiles"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    recurse: yes
    state: directory

- name: Check if ghostty config exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/ghostty"
  register: ghostty_config

- name: Remove ghostty config if it exists
  file:
    path: "{{ ansible_env.HOME }}/.config/ghostty"
    state: absent
  when: ghostty_config.stat.exists

- name: Run stow in dotfiles repo
  shell: |
    stow .
  args:
    chdir: "{{ ansible_env.HOME }}/dotfiles"
  register: stow_result
  changed_when: stow_result.rc == 0

- name: Check if brew.txt exists
  stat:
    path: "{{ ansible_env.HOME }}/dotfiles/brew.txt"
  register: brew_file

- name: Check if README.md exists
  become: true
  stat:
    path: "{{ ansible_env.HOME }}/dotfiles/README.md"
  register: readme_file

- name: Remove brew.txt if it exists
  become: true
  file:
    path: "{{ ansible_env.HOME }}/dotfiles/brew.txt"
    state: absent
  when: brew_file.stat.exists

- name: Remove README.md if it exists
  become: true
  file:
    path: "{{ ansible_env.HOME }}/dotfiles/README.md"
    state: absent
  when: readme_file.stat.exists
