---
# Filesystem and disk management tools
- name: Install filesystem tools
  become: true
  community.general.pacman:
    name:
      - dosfstools
      - ntfs-3g
      - exfat-utils
      - p7zip
      - unzip
    state: present
  changed_when: false