---
- name: Install fonts packages
  become: true
  kewlfft.aur.aur:
    name:
      - ttf-ubuntu-font-family
      - noto-fonts
      - noto-fonts-emoji
      - ttf-dejavu
      - ttf-roboto
      - ttf-cascadia-code-nerd
      - adobe-source-han-sans-otc-fonts
      - ttf-meslo-nerd
      - ttf-inter-nerd
      - ttf-fira-code-nerd
    use: yay
    state: present
  changed_when: false
