- name: Configure git user settings
  become: false
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: "user.email", value: "dzannotti@me.com" }
    - { name: "user.name", value: "Daniele Zannotti" }
    - { name: "init.defaultBranch", value: "main" }
    - { name: "pull.rebase", value: "false" }
    - { name: "push.autoSetupRemote", value: "true" }
    - { name: "core.editor", value: "nvim" }
    - { name: "core.pager", value: "delta" }
    - { name: "interactive.diffFilter", value: "delta --color-only" }
    - { name: "delta.navigate", value: "true" }
    - { name: "delta.light", value: "false" }
    - { name: "delta.side-by-side", value: "true" }
    - { name: "merge.conflictstyle", value: "diff3" }
    - { name: "diff.colorMoved", value: "default" }
