---
- name: Set user avatar for Hyprland lock screen
  copy:
    src: "{{ playbook_dir }}/assets/profile.png"
    dest: "/home/dzannotti/.config/hypr/avatar.png"
    owner: dzannotti
    group: dzannotti
    mode: '0644'
