---
- name: Set user avatar for Hyprland lock screen
  copy:
    src: "{{ playbook_dir }}/assets/profile.png"
    dest: "/home/dzannotti/.config/hypr/avatar.png"
    owner: dzannotti
    group: dzannotti
    mode: '0644'

- name: Install Clipboard utils
  become: true
  kewlfft.aur.aur:
    name:
      - wayclip
    use: yay
    state: present
  changed_when: false
