---
- name: Clone dotfiles repo
  become: true
  git:
    repo: "https://github.com/dzannotti/dotfiles"
    dest: "{{ ansible_env.HOME }}/dotfiles"
    version: master
    update: true

- name: Run stow in dotfiles repo
  shell: |
    stow .
  args:
    chdir: "{{ ansible_env.HOME }}/dotfiles"
  register: stow_result
  changed_when: stow_result.rc == 0
