---
- name: Install microcode (AMD)
  community.general.pacman:
    name:
      - amd-ucode
  become: true
  when: "'AuthenticAMD' in ansible_processor"

- name: Ensure microcode is included in GRUB_CMDLINE_LINUX_DEFAULT for AMD
  become: true
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT=.*"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet amd_ucode=/boot/amd-ucode.img"'
    backrefs: yes
    create: yes

- name: Rebuild GRUB configuration
  become: true
  command: grub-mkconfig -o /boot/grub/grub.cfg
