- name: Ensure [multilib] repo is enabled
  become: true
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?\s*\[multilib\]'
    line: '[multilib]'
    state: present

- name: Ensure multilib mirrorlist is included
  become: true
  lineinfile:
    path: /etc/pacman.conf
    insertafter: '^\[multilib\]'
    regexp: '^#?\s*Include\s*=\s*/etc/pacman.d/mirrorlist'
    line: 'Include = /etc/pacman.d/mirrorlist'
    state: present

- name: Update pacman cache
  become: true
  pacman:
    update_cache: yes
