---
- name: Ensure DKMS and kernel headers are installed
  become: true
  pacman:
    name:
      - dkms
      - linux-headers
    state: present

- name: Install NVIDIA GPU packages
  become: true
  pacman: # ← Use pacman instead of yay for official repo packages
    name:
      - nvidia
      - nvidia-utils
      - lib32-nvidia-utils
      - nvidia-settings
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - libva-utils
      - mesa
      - lib32-mesa
      - vulkan-headers
    state: present
  changed_when: false

- name: Install NVIDIA AUR packages
  become: true
  kewlfft.aur.aur:
    use: yay
    name:
      - nvidia-vaapi-driver
    state: present
