---
- name: Enable sshd
  become: true
  service:
    name: sshd
    enabled: true
  changed_when: false

- name: Enable NetworkManager
  become: true
  service:
    name: NetworkManager
    enabled: true
  changed_when: false

- name: Enable reflector
  become: true
  service:
    name: reflector
    enabled: true
  changed_when: false

- name: Enable bluetooth
  become: true
  service:
    name: bluetooth
    enabled: true
  changed_when: false
