---
- name: Remove conflicting bibata-cursor-theme
  ansible.builtin.pacman:
    name:
      - bibata-cursor-theme
      - bibata-cursor-theme-bin
    state: absent

- name: Install themes
  become: false
  kewlfft.aur.aur:
    name:
      - bibata-cursor-theme-bin
    use: yay
    state: present
    extra_args: "--answerclean Yes --answerdiff None --overwrite '*'"

- name: Copy Sweet SDDM settings
  copy:
    src: "{{ playbook_dir }}/assets/sddm.conf"
    dest: /etc/ssdm.conf
    owner: root
    group: root
    mode: '0755'
