---
- name: Install SDDM
  pacman:
    name:
      - sddm
    state: present

- name: Enable SDDM
  systemd:
    name: sddm
    enabled: true
    state: started

- name: Clone the theme repository
  git:
    repo: https://github.com/Keyitdev/sddm-astronaut-theme.git
    dest: /usr/share/sddm/themes/sddm-astronaut-theme
    version: master

- name: Copy fonts
  copy:
    src: /usr/share/sddm/themes/sddm-astronaut-theme/Fonts/
    dest: /usr/share/fonts/
    remote_src: true

- name: Set SDDM theme
  lineinfile:
    path: /etc/sddm.conf
    regexp: '^Current='
    line: 'Current=sddm-astronaut-theme'

- name: Set virtual keyboard input method
  lineinfile:
    path: /etc/sddm.conf.d/virtualkbd.conf
    regexp: '^InputMethod='
    line: 'InputMethod=qtvirtualkeyboard'

- name: Select theme
  lineinfile:
    path: /usr/share/sddm/themes/sddm-astronaut-theme/metadata.desktop
    regexp: '^ConfigFile='
    line: 'ConfigFile=Themes/your_theme.conf'
