---
- name: Install SDDM
  pacman:
    name:
      - sddm
    state: present

- name: Enable SDDM
  systemd:
    name: sddm
    enabled: true
    state: started

- name: Set default SDDM user
  lineinfile:
    path: /etc/sddm.conf
    line: |
      [General]
      User=dzannotti
      Session=hyprland.desktop
    create: yes
    owner: root
    group: root
    mode: '0644'


- name: Clone Sweet theme repository (nova branch)
  git:
    repo: https://github.com/EliverLara/Sweet.git
    dest: /tmp/sweet-theme
    version: nova
    force: yes

- name: Ensure /usr/share/sddm/themes/Sweet directory exists
  file:
    path: /usr/share/sddm/themes/Sweet
    state: directory
    mode: '0755'

- name: Copy Sweet SDDM theme contents
  copy:
    src: /tmp/sweet-theme/kde/sddm/
    dest: /usr/share/sddm/themes/Sweet/
    owner: root
    group: root
    mode: '0755'

- name: Install Inter Nerd Font
  become: true
  kewlfft.aur.aur:
    name:
      - nerd-fonts-inter
    use: yay
    state: present

- name: Ensure /etc/sddm.conf exists with Sweet theme configuration
  lineinfile:
    path: /etc/sddm.conf
    line: |
      [Theme]
      Current=Sweet
    create: yes
    owner: root
    group: root
    mode: '0644'

- name: Remove temporary Sweet theme repository
  file:
    path: /tmp/sweet-theme
    state: absent

- name: Replace font in Sweet theme.conf with Inter Nerd Font
  replace:
    path: /usr/share/sddm/themes/Sweet/theme.conf
    regexp: '^font=.*'
    replace: 'font=Inter Nerd Font Mono'
