---
- name: Install SDDM
  pacman:
    name:
      - sddm
    state: present

- name: Enable SDDM
  systemd:
    name: sddm
    enabled: true
    state: started

- name: Install accountsservice
  pacman:
    name: accountsservice
    state: present

- name: Enable and start accounts-daemon
  systemd:
    name: accounts-daemon
    enabled: yes
    state: started

- name: Ensure AccountsService icons directory exists
  file:
    path: /var/lib/AccountsService/icons/{{ ansible_user_id }}
    state: directory
    mode: '0755'

- name: Set user avatar for SDDM
  copy:
    src: "{{ playbook_dir }}/assets/profile.png"
    dest: "/var/lib/AccountsService/icons/dzannotti.png"
    owner: root
    group: root
    mode: '0644'
