---
- name: Create themes directory structure
  file:
    path: "/home/{{ lookup('env', 'USER') }}/.oh-my-zsh/themes/catppuccin-flavors"
    state: directory
    mode: '0755'

- name: Clone Catppuccin ZSH theme repo
  ansible.builtin.git:
    repo: "https://github.com/JannoTjarks/catppuccin-zsh.git"
    dest: "/home/{{ lookup('env', 'USER') }}/.catppuccin-zsh"
    version: main
    depth: 1
    update: true
    force: false
  register: theme_clone
  changed_when: theme_clone.changed

- name: Create theme symlinks
  file:
    src: "/home/{{ lookup('env', 'USER') }}/.catppuccin-zsh/{{ item.src }}"
    dest: "/home/{{ lookup('env', 'USER') }}/.oh-my-zsh/themes/{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "catppuccin.zsh-theme", dest: "catppuccin.zsh-theme" }
    - { src: "catppuccin-flavors", dest: "catppuccin-flavors" }

- name: Add theme source to .zshrc
  lineinfile:
    path: "/home/{{ lookup('env', 'USER') }}/.zshrc"
    line: "source /home/{{ lookup('env', 'USER') }}/.zsh_theme"
    state: present
    insertafter: EOF
