---
# ZSH is already installed in base.yml
- name: Set user shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true

- name: Check if oh-my-zsh is installed
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_dir

- name: Download and install oh-my-zsh
  become: false
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  when: not ohmyzsh_dir.stat.exists
  changed_when: true

- name: Ensure ~/.config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'
  become: false

- name: Initialize starship prompt
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^eval "\$\(starship init zsh\)"'
    line: 'eval "$(starship init zsh)"'
    state: present
    insertafter: EOF
  become: false

- name: Configure zoxide integration
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^eval "\$\(zoxide init zsh\)"'
    line: 'eval "$(zoxide init zsh)"'
    state: present
    insertafter: EOF
  become: false
